{
  "build": "py39hca03da5_0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/osx-arm64",
  "constrains": [],
  "depends": [
    "python >=3.9,<3.10.0a0"
  ],
  "extracted_package_dir": "/opt/homebrew/Caskroom/miniconda/base/pkgs/exceptiongroup-1.2.0-py39hca03da5_0",
  "files": [
    "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/INSTALLER",
    "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/LICENSE",
    "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/METADATA",
    "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/RECORD",
    "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/REQUESTED",
    "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/WHEEL",
    "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/direct_url.json",
    "lib/python3.9/site-packages/exceptiongroup/__init__.py",
    "lib/python3.9/site-packages/exceptiongroup/__pycache__/__init__.cpython-39.pyc",
    "lib/python3.9/site-packages/exceptiongroup/__pycache__/_catch.cpython-39.pyc",
    "lib/python3.9/site-packages/exceptiongroup/__pycache__/_exceptions.cpython-39.pyc",
    "lib/python3.9/site-packages/exceptiongroup/__pycache__/_formatting.cpython-39.pyc",
    "lib/python3.9/site-packages/exceptiongroup/__pycache__/_suppress.cpython-39.pyc",
    "lib/python3.9/site-packages/exceptiongroup/__pycache__/_version.cpython-39.pyc",
    "lib/python3.9/site-packages/exceptiongroup/_catch.py",
    "lib/python3.9/site-packages/exceptiongroup/_exceptions.py",
    "lib/python3.9/site-packages/exceptiongroup/_formatting.py",
    "lib/python3.9/site-packages/exceptiongroup/_suppress.py",
    "lib/python3.9/site-packages/exceptiongroup/_version.py",
    "lib/python3.9/site-packages/exceptiongroup/py.typed"
  ],
  "fn": "exceptiongroup-1.2.0-py39hca03da5_0.conda",
  "license": "MIT",
  "link": {
    "source": "/opt/homebrew/Caskroom/miniconda/base/pkgs/exceptiongroup-1.2.0-py39hca03da5_0",
    "type": 1
  },
  "md5": "3ea50ebb5ca4690920c583f6052e73c6",
  "name": "exceptiongroup",
  "package_tarball_full_path": "/opt/homebrew/Caskroom/miniconda/base/pkgs/exceptiongroup-1.2.0-py39hca03da5_0.conda",
  "paths_data": {
    "paths": [
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/INSTALLER",
        "path_type": "hardlink",
        "sha256": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "sha256_in_prefix": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "size_in_bytes": 5
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/LICENSE",
        "path_type": "hardlink",
        "sha256": "6e5070d765031e0ad403a1cbf90ae6d19a0228f802e320b7acff460aa72ed47c",
        "sha256_in_prefix": "6e5070d765031e0ad403a1cbf90ae6d19a0228f802e320b7acff460aa72ed47c",
        "size_in_bytes": 3704
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/METADATA",
        "path_type": "hardlink",
        "sha256": "1d998cf5f14e54cf261360d854a049606682f73813b6a22d1b1d7bd51f17ba2e",
        "sha256_in_prefix": "1d998cf5f14e54cf261360d854a049606682f73813b6a22d1b1d7bd51f17ba2e",
        "size_in_bytes": 6603
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/RECORD",
        "path_type": "hardlink",
        "sha256": "09d252e92549300ce46575f9426bcee5727fa9cb580b375190e87efaf31d944c",
        "sha256_in_prefix": "09d252e92549300ce46575f9426bcee5727fa9cb580b375190e87efaf31d944c",
        "size_in_bytes": 1536
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/REQUESTED",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/WHEEL",
        "path_type": "hardlink",
        "sha256": "1196c6921ec87b83e865f450f08d19b8ff5592537f4ef719e83484e546abe33e",
        "sha256_in_prefix": "1196c6921ec87b83e865f450f08d19b8ff5592537f4ef719e83484e546abe33e",
        "size_in_bytes": 81
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup-1.2.0.dist-info/direct_url.json",
        "path_type": "hardlink",
        "sha256": "466f04464c995efffcba898b356918a0b196a7b0e1f9ef0b2988dbfe7c34590c",
        "sha256_in_prefix": "466f04464c995efffcba898b356918a0b196a7b0e1f9ef0b2988dbfe7c34590c",
        "size_in_bytes": 145
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/__init__.py",
        "path_type": "hardlink",
        "sha256": "ec31d2d210e4f9122cdc841cdd26d9541d3ed4c86248227d5e0bc4c849682fb3",
        "sha256_in_prefix": "ec31d2d210e4f9122cdc841cdd26d9541d3ed4c86248227d5e0bc4c849682fb3",
        "size_in_bytes": 1049
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/__pycache__/__init__.cpython-39.pyc",
        "path_type": "hardlink",
        "sha256": "8562f9b70239701ffb5dca903c1e9899229a6d7a4dd5e74c993837d471653369",
        "sha256_in_prefix": "8562f9b70239701ffb5dca903c1e9899229a6d7a4dd5e74c993837d471653369",
        "size_in_bytes": 839
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/__pycache__/_catch.cpython-39.pyc",
        "path_type": "hardlink",
        "sha256": "eb61c7c3141ac497e09b9b7190dee7195a6e79f813b229e1a4ab4c2bb9b1f028",
        "sha256_in_prefix": "eb61c7c3141ac497e09b9b7190dee7195a6e79f813b229e1a4ab4c2bb9b1f028",
        "size_in_bytes": 3192
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/__pycache__/_exceptions.cpython-39.pyc",
        "path_type": "hardlink",
        "sha256": "acb45aedab733e150fb4302c03bde88ebbd4a544d2f4ebad03cb28e911e11ee0",
        "sha256_in_prefix": "acb45aedab733e150fb4302c03bde88ebbd4a544d2f4ebad03cb28e911e11ee0",
        "size_in_bytes": 9294
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/__pycache__/_formatting.cpython-39.pyc",
        "path_type": "hardlink",
        "sha256": "ac8f60d4453290f58544acebe208efec4db041a557589ff427ccc7cb21edddca",
        "sha256_in_prefix": "ac8f60d4453290f58544acebe208efec4db041a557589ff427ccc7cb21edddca",
        "size_in_bytes": 11850
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/__pycache__/_suppress.cpython-39.pyc",
        "path_type": "hardlink",
        "sha256": "8d25a11539aaa8beb04c9fb9f208e959f360eab02f15a5df1f734e3cbb8e2321",
        "sha256_in_prefix": "8d25a11539aaa8beb04c9fb9f208e959f360eab02f15a5df1f734e3cbb8e2321",
        "size_in_bytes": 1083
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/__pycache__/_version.cpython-39.pyc",
        "path_type": "hardlink",
        "sha256": "ebe4bf4dc9ecb7ce41bec9230f1e39723ac2165362cdda8352437c18bcc047c2",
        "sha256_in_prefix": "ebe4bf4dc9ecb7ce41bec9230f1e39723ac2165362cdda8352437c18bcc047c2",
        "size_in_bytes": 240
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/_catch.py",
        "path_type": "hardlink",
        "sha256": "926c74d4b904648e7ea66c61f404c43b8bf3a80b649fb9e357ee59f85d0aa7e2",
        "sha256_in_prefix": "926c74d4b904648e7ea66c61f404c43b8bf3a80b649fb9e357ee59f85d0aa7e2",
        "size_in_bytes": 4669
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/_exceptions.py",
        "path_type": "hardlink",
        "sha256": "7fe58e5c7c3e9555800198c663c73e285c687c2bc37049785de3037aa7203328",
        "sha256_in_prefix": "7fe58e5c7c3e9555800198c663c73e285c687c2bc37049785de3037aa7203328",
        "size_in_bytes": 11010
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/_formatting.py",
        "path_type": "hardlink",
        "sha256": "9ae98881193ad6d86fef03fa5b30a954db063e16191967df25e1b34278052f4b",
        "sha256_in_prefix": "9ae98881193ad6d86fef03fa5b30a954db063e16191967df25e1b34278052f4b",
        "size_in_bytes": 21005
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/_suppress.py",
        "path_type": "hardlink",
        "sha256": "f3298ac7900570ed79178ecd7e7448f86f7c9a7e19057bb2b78aa22dde730f74",
        "sha256_in_prefix": "f3298ac7900570ed79178ecd7e7448f86f7c9a7e19057bb2b78aa22dde730f74",
        "size_in_bytes": 1338
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/_version.py",
        "path_type": "hardlink",
        "sha256": "0a29461f271247399212708c42f4d127927f2d6c4cb3efbe52a9156ce990dab0",
        "sha256_in_prefix": "0a29461f271247399212708c42f4d127927f2d6c4cb3efbe52a9156ce990dab0",
        "size_in_bytes": 160
      },
      {
        "_path": "lib/python3.9/site-packages/exceptiongroup/py.typed",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      }
    ],
    "paths_version": 1
  },
  "requested_spec": "None",
  "sha256": "0d80b76cef0a8afae9c93cc4d79fd1234b18fae6c9d4a1235579e23649a1c140",
  "size": 31354,
  "subdir": "osx-arm64",
  "timestamp": 1706031434000,
  "url": "https://repo.anaconda.com/pkgs/main/osx-arm64/exceptiongroup-1.2.0-py39hca03da5_0.conda",
  "version": "1.2.0"
}